blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailsender.urls', namespace='mailsender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, UsersListView, UserDetailView, UserUpdateView, \
    UserMailConfirmView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_email', UserMailConfirmView.as_view(), name='confirm_email'),
    path('verify/<str:key>/', verify_email, name='verify_email'),
    path('users_list/', UsersListView.as_view(), name='users_list'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='user_update')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):

    STATUS_ACTIVE = 'active'
    STATUS_BLOCKED = 'blocked'
    STATUSES = [
        (STATUS_ACTIVE, 'активен'),
        (STATUS_BLOCKED, 'заблокирован'),
    ]
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    email_is_confirmed = models.BooleanField(default=False, verbose_name='подтверждено')
    email_confirm_key = models.CharField(max_length=30, verbose_name='код подтверждения почты', **NULLABLE)
    status = models.CharField(max_length=15, choices=STATUSES, default=STATUS_BLOCKED, verbose_name='статус пользователя')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'
        permissions = [
            ('block_another_user', 'Can block another user'),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.utils.crypto import get_random_string
from mailsender.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "password1", "password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        if not user.email_confirm_key:
            user.email_confirm_key = get_random_string(length=8)
        if commit:
            user.save()
        return user


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "password", "first_name", "last_name"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserStatusForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ['email', 'status']

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView, DetailView, ListView

from config import settings
from users.forms import UserForm, UserRegisterForm, UserStatusForm
from users.models import User


class UsersListView(LoginRequiredMixin,PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'
    template_name = 'users/users_list.html'


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users:users_list')
    form_class = UserStatusForm
    permission_required = 'users.block_another_user'

    def get_object(self, queryset=None):
        return self.request.user


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:confirm_email')
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = form.save()
        email_confirm_key = self.object.email_confirm_key
        email_confirm_url = self.request.build_absolute_uri(
            reverse("users:verify_email", kwargs={"key": email_confirm_key}))
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Для завершения регистрации, пожалуйста, перейдите по ссылке: {email_confirm_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email],
        )
        return redirect(self.success_url)


class ProfileView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def test_func(self):
        user = self.request.user
        object = self.get_object()
        if user.is_superuser or user.email == object.email:
            return True
        return False


class UserDetailView(DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user


def verify_email(request, key):
    user = get_object_or_404(User, email_confirm_key=key)
    user.status = 'active'
    user.email_confirm_key = ''
    user.save()
    return redirect('users:login')

class UserMailConfirmView(RegisterView):
    template_name = 'users/confirm_email.html'

users/templates/users/confirm_email.html
{% extends 'mailsender/base.html' %}

{% block content%}

        <h2>Поздравляем с регистрацией!</h2>
<p>На Ваш почтовый ящик отправлено письмо со ссылкой</p>
<p>Для завершения регистрации перейдите, пожалуйста, по ссылке, указанной в письме</p>

{% endblock %}

users/templates/users/login.html
{% extends 'mailsender/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-3">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailsender/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-3">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailsender/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-4"></div>
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                <h6>Профиль пользователя</h6>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-info">Сохранить</button>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_update.html
{% extends 'mailsender/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-4"></div>
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                <h6>Профиль пользователя</h6>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/users_list.html
{% extends 'mailsender/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        {% for user in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card">

                <div class="card-body">
                    <h5 class="card-title">{{ user.name }} </h5>
                    <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>

                    <p class="card-text"><strong>Статус:</strong> {% if user.status == 'active' %}Активен{% else %}Заблокирован{% endif %}</p>
                    {% if perms.users.block_another_user %}
                    <a href="{% url 'users:user_update' user.pk %}" class="btn btn-primary">Изменить статус пользователя</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}