blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailsender.urls', namespace='mailsender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailsender/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailsender.apps import MailsenderConfig
from mailsender.views import MailingListView, ClientCreateView, MailingCreateView, IndexView, \
    ClientUpdateView, MailingUpdateView, MailingDeleteView, ClientDeleteView, MailingDetailView, MailingLogsView, \
    MailingManagerUpdateView # mailing_logs

app_name = MailsenderConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),

    path('edit_client/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('edit_mailing/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('delete_mailing/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('mailing_detail/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailinglogs', MailingLogsView.as_view(), name='mailinglogs'),
    path('manager_edit_mailing/<int:pk>', MailingManagerUpdateView.as_view(), name='manager_mailing_update'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, UsersListView, UserDetailView, UserUpdateView, \
    UserMailConfirmView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_email', UserMailConfirmView.as_view(), name='confirm_email'),
    path('verify/<str:key>/', verify_email, name='verify_email'),
    path('users_list/', UsersListView.as_view(), name='users_list'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='user_update')
]

mailsender/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import time, datetime

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):

    email = models.CharField(max_length=100, verbose_name='электронный адрес')
    name = models.CharField(max_length=50, verbose_name='имя получателя')
    comment = models.TextField(verbose_name='комментарий', null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец клиента', **NULLABLE)

    def __str__(self):
        return f'Email: {self.email} ({self.name})'

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"

class Mailing(models.Model):
    FREQUENCY_CHOICES = [
        ('daily', 'ежедневно'),
        ('weekly', 'еженедельно'),
        ('monthly', 'ежемесячно'),
    ]

    STATUS_CHOICES = [
        ('created', 'создана'),
        ('running', 'запущена'),
        ('completed', 'завершена'),
    ]
    name = models.CharField(max_length=50, verbose_name='название', default='MyMailing')
    start_time = models.TimeField(default=timezone.now, verbose_name='Время запуска рассылки')
    next_start = models.DateField(default=timezone.now, verbose_name='дата запуска рассылки')
    stop_time = models.TimeField(default=timezone.now, verbose_name='Время завершения рассылки')
    frequency = models.CharField(max_length=15, default='ежемесячно', choices=FREQUENCY_CHOICES, verbose_name='периодичность')
    status = models.CharField(max_length=15, default='создана', choices=STATUS_CHOICES, verbose_name='статус рассылки')
    client = models.ManyToManyField(Client, **NULLABLE, verbose_name='подписчики')
    title = models.CharField(max_length=50, verbose_name='тема письма', default='Message Title')
    body = models.TextField(verbose_name='тело письма', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Статус активности')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец рассылки',
                              **NULLABLE)
    def get_status(self):
        now = datetime.now().time()
        print(self.start_time)
        print(now)
        print(self.stop_time)
        if self.start_time < now < self.stop_time:
            self.status = "running"

            self.save()
        return self.status


    def __str__(self):
        return f"{self.name}"


    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [
            ('change_mailing_status', 'Can change mailing status'),
        ]


class MailingLogs(models.Model):

    STATUSES = [
        ('ok', 'Успешно'),
        ('failed', 'Ошибка'),
    ]

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')
    last_try = models.DateTimeField(verbose_name='дата и время последней попытки', null=True, blank=True)
    status = models.CharField(max_length=15, choices=STATUSES, default='ok', verbose_name='статус попытки')

    def __str__(self):
        return self.last_try


    class Meta:
        verbose_name = "Лог"
        verbose_name_plural = "Логи"

mailsender/forms.py
from django import forms

from mailsender.models import Mailing, Client


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        fields = ('name', 'title', 'body', 'next_start', 'start_time', 'stop_time', 'frequency', 'status', 'client')


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = ('email', 'name', 'comment')


class ManagerUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        fields = ('status',)

mailsender/views.py
import random
from blog.utils import blog_cache

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from blog.models import Blog
from mailsender.forms import ClientForm, MailingForm, ManagerUpdateForm
from mailsender.models import Client, Mailing, MailingLogs
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView


class IndexView(TemplateView):
    template_name = 'mailsender/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        mailing_count = Mailing.objects.count()
        context['mailing_count'] = mailing_count

        active_mailings = Mailing.objects.filter(status='created').count()
        context['active_mailings'] = active_mailings

        unique_clients = Client.objects.count()
        context['unique_clients'] = unique_clients

        all_blogs = list(blog_cache())
        print(all_blogs)

        if len(all_blogs) >= 3:
            random_blogs = random.sample(all_blogs, 3)
        else:
            random_blogs = all_blogs

        context['random_blogs'] = random_blogs

        return context


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailsender:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailsender:index')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailsender:index')


class MailingListView(ListView):
    model = Mailing

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='Managers').exists() or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                owner=user.pk
            )
        return queryset


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailsender:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailsender:index')


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailsender:index')


class MailingDetailView(DetailView):
    model = Mailing


class MailingLogsView(LoginRequiredMixin, ListView):
    model = MailingLogs
    template_name = 'mailsender/mailinglog_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        return queryset


class MailingManagerUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = ManagerUpdateForm
    success_url = reverse_lazy('mailsender:mailing_list')
    permission_required = 'mailsender.change_mailing_status'

mailsender/templates/mailsender/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        <img src="{% static 'media/logo.jpg' %}" width="110" height="100">
    </h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailsender:index' %}">Главная страница</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailsender:mailing_list' %}">Наши рассылки</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>

        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:users_list' %}">Список пользователей сервиса</a>
        {% endif %}

        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Blog</a>



    </nav>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>

            {% block content %}
            {% endblock %}

        </div>
    </div>
</div>


<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Хайдукова и Ко&copy; {% now 'Y' %}</p>

    </div>
</footer>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailsender/templates/mailsender/client_confirm_delete.html
{% extends 'mailsender/base.html' %}

{% block content %}
<div class="col-12" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {%csrf_token%}
                        <p>Хотите удалить клиента "{{ object.email }}", "{{ object.name }}" ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'maiisender:clients' %}" class="btn btn-warning" >Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailsender/templates/mailsender/client_form.html
{% extends 'mailsender/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            {% if object %}
                            Редактирование данных клиента
                            {% else %}
                            Добавление клиента
                            {% endif %}
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>

</form>
{% endblock %}

mailsender/templates/mailsender/client_list.html
{% extends 'catalog/base.html' %}

{% block content %}


<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:product_form' %}">Добавить продукт</a>

    {% endif %}
</div>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">

                    <div class="card-body">
                        <p class="card-text">{{ object }}</p>
                        <p class="card-text">{{ object.owner }}</p>

                        <p class="card-text">
                            {{ object.description|truncatechars:50 }}
                        </p>
                        <img src="{% mediapath object.preview %}" width="100" height="111">


                        <div class="card-footer">
                            {% if object.active_version_name %}
                            <p>Номер активной версии: {{ object.active_version_number }}<br>
                                Название: {{ object.active_version_name }}</p>
                            {% else %}
                            <p>Номер активной версии: отсутствует <br>
                                Название: отсутствует </p>
                            {% endif %}
                        </div>


                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if user.is_authenticated %}
                                <a href="{% url 'catalog:product_detail' object.id %}"
                                   class="p-2 btn btn-outline-primary">Купить</a>
                                {% else %}
                                <a href="{% url 'users:login' %}"
                                   class="p-2 btn btn-outline-primary">Купить</a>
                                {% endif %}
                                {% if user.is_authenticated %}
                                <a href="{% url 'catalog:product_update' object.id %}"
                                   class="p-2 btn btn-outline-primary">Изменить</a>
                                {% else %}
                                <a href="{% url 'users:login' %}"
                                   class="p-2 btn btn-outline-primary">Изменить</a>
                                {% endif %}
                                {% if perms.catalog.delete_product %}
                                <a href="{% url 'catalog:product_confirm_delete' object.id %}"
                                   class="p-2 btn btn-outline-primary">Удалить</a>

                                {% endif %}


                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>

mailsender/templates/mailsender/index.html
{% extends 'mailsender/base.html' %}

{% block content%}

<div class="jumbotron jumbotron-fluid hero">
    <div class="container">
        <h1 class="display-4">Сервис управления рассылками</h1>
        <p class="lead">Поможет Вам поддерживать интерес клиентов.</p>
        <div class="buttons">

            <p class="lead">
                {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg" href="{% url 'mailsender:create_client' %}" role="button">Добавить клиента</a>
                <a class="btn btn-primary btn-lg" href="{% url 'mailsender:create_mailing' %}" role="button">Создать рассылку</a>
                {% else %}
                <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}" role="button">Добавить клиента</a>
                <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}" role="button">Создать рассылку</a>
                {% endif %}
            </p>

        </div>
    </div>
</div>
<p>
            <h5 class="display-4">Количество рассылок всего: {{ mailing_count }}<br>
            Количество активных рассылок: {{ active_mailings }}<br>
            Количество уникальных клиентов для рассылок: {{ unique_clients }}<br></h5>
            </p>

<div id="home-cta" class="jumbotron jumbotron-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-auto">
                <i class="fas fa-bullhorn"></i>
            </div>
            <div class="col-sm">
                <h3>Хотите побольше узнать о пользе рассылок?</h3>
                <p>Узнайте больше о возможностях контактов с клиентами через рассылки, способах увеличения продаж и сбора данных в нашем блоге.</p>

            <div class="col-md-auto">
                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="{% url 'blog:list' %}" role="button">Перейти в блог</a>
                    {% for blog in random_blogs %}
                <li>
                    <a href="{% url 'blog:view' blog.pk %}">{{ blog.title }}</a>
                </li> {% endfor %}
                </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- 3-C ICON -->
<div id="services" class="container-fluid primary-section blue">
    <div class="container">
        <h2 class="section-title">Наши рассылки</h2>
        <hr class="my-10">
        <p class="section-flavor">Достигайте новых высот</p>
        <div class="row">
            {% for mailing in mailing_list %}
            <div class="col-sm">
                <div class="card">
                    <div class="card-body">
                        <i class="fas fa-chart-line"></i>
                        <h3>{{ mailing.name }}</h3>
                        <p class="card-text">{{ mailing.owner }}</p>

                    </div>
                    <div class="card-footer">
                        <p class="lead">
                            <a class="btn btn-link" href="{% url 'mailsender:mailing_detail' mailing.id %}" role="button">Узнать подробнее</a>
                            {% if user.is_authenticated %}
                            <a class="btn btn-link" href="{% url 'mailsender:mailing_update' mailing.id %}" role="button">Изменить</a>
                            {% endif %}
                            {% if perms.mailing.block_mailing %}
                            <a class="btn btn-link" href="{% url 'mailsender:mailing_update' mailing.id %}" role="button">Заблокировать</a>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>




{% endfor %}
{% endblock %}

mailsender/templates/mailsender/mailing_confirm_delete.html
{% extends 'mailsender/base.html' %}

{% block content %}
<div class="col-12" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {%csrf_token%}
                        <p>Хотите удалить рассылку "{{ object.name }}"" ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailsender:mailing_list' %}" class="btn btn-warning" >Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailsender/templates/mailsender/mailing_detail.html
{% extends 'mailsender/base.html' %}

{% block content%}

    <div class="container">
        <div class="row">

            <div class="col-md-4">
                <h2>{{ object.name }}</h2>
                <p>Дата отправки: {{ object.sending_time }}</p>
                <p>Периодичность: {{ object.frequency }} руб.</p>
                <p>Клиенты, подписанные на рассылку: {{ object.client.all }} </p>
                <div class="">


                        <a href="{% url 'mailsender:mailing_update' object.id %}" type="button" class="btn btn-outline-primary">изменить</a>


                        <a href="{% url 'mailsender:delete_mailing' object.id %}" type="button" class="btn btn-outline-primary">удалить</a>


                    </div>

            </div>
<div class="col-6">

        </div>
    </div>
{% endblock %}

mailsender/templates/mailsender/mailing_form.html
{% extends 'mailsender/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            {% if object %}
                            Редактирование рассылки
                            {% else %}
                            Создание рассылки
                            {% endif %}
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>

</form>
{% endblock %}

mailsender/templates/mailsender/mailing_list.html
{% extends 'mailsender/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Наши рассылки</h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'mailsender:mailinglogs' %}">Mailing Logs</a>
</div>

{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">

            <p class="card-text">

                {{ object.name }}
            </p>
            <p class="card-text">
            {{ object.frequency }}, {{ object.status }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.mailsender.change_mailing_status %}
                    <a href="{% url 'mailsender:manager_mailing_update' object.id %}"
                       class="btn btn-sm btn-outline-secondary">Редактировать статус рассылки</a>
                    {% endif %}

                    {% if user.is_authenticated and object.owner == user %}

                    <a href="{% url 'mailsender:mailing_detail' object.id %}"
                       class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                    <a href="{% url 'mailsender:mailing_update' object.id %}"
                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'mailsender:delete_mailing' object.id %}"
                       class="btn btn-sm btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

mailsender/templates/mailsender/mailinglog_list.html
{% extends 'mailsender/base.html' %}

{% block content %}
    <div>
        <div class="row mt-2">
            <div class="col m-2"><br>
                <h2 align="center">Список логов рассылки</h2>

                    <br>
                    <br>
                    <table class="table">
                        <thead>

                            <th>№</th>
                            <th>Рассылка</th>
                            <th>Время последней попытки</th>
                            <th>Статус попытки</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ object.mailing.name }}</td>
                                <td>{{ object.last_try }}</td>


                                {% if object.status == 'ok' %}
                                    <td class="text-success">{{ object.status }}</td>
                                {% elif object.status == 'failed' %}
                                    <td class="text-danger">{{ object.status }}</td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                <br>


            </div>
        </div>
    </div>
{% endblock %}

mailsender/templates/mailsender/message_form.html
{% extends 'mailsender/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            {% if object %}
                            Редактирование сообщения
                            {% else %}
                            Создание сообщения для рассылки
                            {% endif %}
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>

</form>
{% endblock %}